### ISSUE TITLE
project plan

### ISSUE THREAD

**Issue by MuYunyun** [MuYunyun/blog#42]
### RFC

- [ ] to build visualization site to show every .md file.
  - [ ] create-react-doc start;
  - [ ] create-react-doc build;
  - [ ] create-react-doc upload;
  - [ ] lint;

For example, the root has React dir, the site should has a menu name called React.

### HOW TO USE

```js
yarn add seed

// perf
seed start
```

And then you'll see the blog run in the localhost: 3000.

**Comment by MuYunyun** [comment]
if have any idea, welcome advise there.

**Comment by MuYunyun** [comment]
The issue has moved to [there](https://github.com/MuYunyun/create-react-doc/issues/1)
